apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: dev
images:
- name: ghcr.io/fabiovangeel/cloudops-cicd
  newName: ghcr.io/fabiovangeel/cloudops-cicd
  newTag: sha-1d8b28cffa757926dabe0ad09f5610b963d070c0
